### PR TITLE
here's the fix ;)

### PR DESCRIPTION
**Pull request by hguy**

### CODE REVIEW

**Comment by hguy** [comment]
it should be easier to compare using a github PR

**Comment by AirsQ** [comment]
> it should be easier to compare using a github PR
Hi, I just had a  test today. I'm too busy these days.
At first, this really more simplified. For example: the cultureID field. Thank you so much for optimizing code.

Everything is OK, but there still have a question that handling '[' and ']'  symbol in Chinese.
The problem is that [] symbol should't be discarded when getting value of  (tagRelic and tagCharm).
This problem is caused by me. I don't communicate clearly in code comments. Sorry.
In Chinese, almost name of (Relic and Charm) ends with "[xxx]" which is all meaningful. 

In localization file:



In TQ:







In Vault what I expect: 


In Vault after fix:

There is no [] symbol.

I want to fix it.
But I don't know much about other languages。
I'm afraid my fix will affect other language processing。

Do you have any experience or opinions？

Look forward to your reply。

By the way, now, that's the only question. Can't wait for Chinese version TQVault!

**Comment by AirsQ** [comment]
> it should be easier to compare using a github PR

**Comment by AirsQ** [comment]
> > it should be easier to compare using a github PR
> > Hi, I just had a  test today. I'm too busy these days.
> > At first, this really more simplified. For example: the cultureID field. Thank you so much for optimizing code.
> 
> Everything is OK, but there still have a question that handling '[' and ']' symbol in Chinese. The problem is that [] symbol should't be discarded when getting value of (tagRelic and tagCharm). This problem is caused by me. I don't communicate clearly in code comments. Sorry. In Chinese, almost name of (Relic and Charm) ends with "[xxx]" which is all meaningful.
> 
> In localization file:  
> 
> In TQ:      
> 
> In Vault what I expect: 
> 
> In Vault after fix:  There is no [] symbol.
> 
> I want to fix it. But I don't know much about other languages。 I'm afraid my fix will affect other language processing。
> 
> Do you have any experience or opinions？
> 
> Look forward to your reply。
> 
> By the way, now, that's the only question. Can't wait for Chinese version TQVault!


@hguy  there still have a question.

**Comment by hguy** [comment]
Hi ! 
I didn't know this was meaningfull.

Here's the logic of the cleaning part

```csharp
if (Regex.Match(label, @"^(?<Tag>\[\w+\])(?<Label>[^\\[]+)|^\[(?<Label>[^\]]+)\]$") is { Success: true } match)
	label = match.Groups["Label"].Value.Trim();
else
	label = label.Replace("[", string.Empty).Replace("]", string.Empty).Trim();
```

#Regex Match (really meaningful)
"[右键 - 喝]" => "右键 - 喝"
"[Faites un clic droit pour boire]" => "Faites un clic droit pour boire"
"[ms]renforcé[mp]renforcés[fs]renforcée[fp]renforcées" => "renforcé"
"[ms]renforcé" => "renforcé"

#Replace Match (just for cleaning in between brackets not very meaningful in latin language)
"Requiert {%s0}: {%.0f1} [ {^r%.0f2 ^y- %.0f3}% de réduction]" => "Requiert {%s0}: {%.0f1}  {^r%.0f2 ^y- %.0f3}% de réduction"

**Solution** : Remove both "label.Replace()" it's no problem for latin and it's a big deal for chinese.

**Comment by AirsQ** [comment]
Thanks!

**Pull request merged**
